// Fælles datakilde for alle datoer på siden.
// Både forsidens tidslinje, nedtællingen øverst og månedskalenderen
// (kalender.html) genereres af build.mjs ud fra denne ene liste, så en
// dato kun skal rettes ét sted.
//
// Felter pr. begivenhed:
//   start      ISO-dato (YYYY-MM-DD)
//   kind       frist | samtale | tiltraedelse (styrer farve i kalenderen)
//   abbr       kort bogstav-mærke i kalenderen der viser stillingen (tom = intet)
//   tag        pille-klasse på forsiden (tag--sendt, tag--samtale, ...)
//   tagLabel   teksten i pillen
//   heading    overskrift i tidslinjen
//   headingUrl gør overskriften til et link (udelad for ingen link)
//   desc       brødtekst i tidslinjen
//   calTitle   titel i .ics og som tooltip i kalenderen
//   calDesc    beskrivelse i .ics
//   calUrl     link lagt i .ics (udelad for ingen)
//   cdLabel    hvis sat, indgår datoen i nedtællingen med denne tekst

export const events = [
  {
    start: '2026-08-11',
    kind: 'frist',
    abbr: 'V',
    tag: 'sendt',
    tagLabel: '✓ Sendt 11. juli',
    heading: 'Skoleleder · Vonsild Specialskole',
    headingUrl: 'vonsild.html',
    desc: 'Kolding Kommune. Ansøgning og CV er sendt 11. juli 2026, en måned før fristen.',
    calTitle: 'Ansøgningsfrist: Skoleleder · Vonsild Specialskole',
    calDesc: 'Kolding Kommune. Ansøgning og CV er sendt 11. juli 2026, en måned før fristen.',
    calUrl: 'vonsild.html',
  },
  {
    start: '2026-08-11',
    kind: 'frist',
    abbr: 'S',
    tag: 'sendt',
    tagLabel: '✓ Sendt 7. juli',
    heading: 'Ungecenterleder · Sønderborg Kommune',
    headingUrl: 'soenderborg.html',
    desc: 'Ansøgning og CV er sendt 7. juli 2026, i god tid før fristen.',
    calTitle: 'Ansøgningsfrist: Ungecenterleder · Sønderborg',
    calDesc: 'Ansøgning og CV er sendt 7. juli 2026, i god tid før fristen.',
    calUrl: 'soenderborg.html',
  },
  {
    start: '2026-08-19',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: '1. samtale',
    heading: 'Ungecenterleder · Sønderborg',
    headingUrl: 'soenderborg.html',
    desc: 'Første samtale med case på ungeområdet.',
    calTitle: '1. samtale: Ungecenterleder · Sønderborg',
    calDesc: 'Første samtale med case på ungeområdet.',
    calUrl: 'soenderborg.html',
    cdLabel: '1. samtale: Sønderborg og Vonsild',
  },
  {
    start: '2026-08-19',
    kind: 'samtale',
    abbr: 'V',
    tag: 'samtale',
    tagLabel: '1. samtale · kl. 17.00',
    heading: 'Skoleleder · Vonsild',
    headingUrl: 'vonsild.html',
    desc: 'Bekræftet. Kl. 17.00, 45 minutter, Vonsild Skole - Specialcenter Vonsild. Invitation accepteret 14. august. Motivation, ledelsessyn og værdimatch.',
    calTitle: '1. samtale: Skoleleder · Vonsild (kl. 17.00)',
    calDesc: 'Bekræftet. Kl. 17.00, 45 minutter. Motivation, ledelsessyn og værdimatch.',
    calUrl: 'vonsild.html',
  },
  {
    start: '2026-08-24',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: '2. samtale',
    heading: 'Ungecenterleder · Sønderborg',
    headingUrl: 'soenderborg.html',
    desc: 'Anden samtale med Garuda-profil. Udfyld spørgeskemaet i forvejen.',
    calTitle: '2. samtale: Ungecenterleder · Sønderborg',
    calDesc: 'Anden samtale med Garuda-profil. Udfyld spørgeskemaet i forvejen.',
    calUrl: 'soenderborg.html',
    cdLabel: '2. samtale: Sønderborg (Garuda)',
  },
  {
    start: '2026-08-25',
    kind: 'samtale',
    abbr: 'V',
    tag: 'samtale',
    tagLabel: '2. samtale',
    heading: 'Skoleleder · Vonsild',
    headingUrl: 'vonsild.html',
    desc: 'Case og ofte personprofiltest.',
    calTitle: '2. samtale: Skoleleder · Vonsild',
    calDesc: 'Case og ofte personprofiltest.',
    calUrl: 'vonsild.html',
    cdLabel: '2. samtale: Vonsild (case)',
  },
  {
    start: '2026-08-31',
    kind: 'frist',
    abbr: 'T',
    tag: 'sendt',
    tagLabel: '✓ Sendt 2. august',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Ansøgning og CV er sendt 2. august 2026, næsten en måned før fristen, og modtagelsen er bekræftet.',
    calTitle: 'Ansøgningsfrist: Bestyrelsesmedlem · tvSyd',
    calDesc: 'Ansøgning og CV er sendt 2. august 2026, næsten en måned før fristen.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-09-04',
    kind: 'frist',
    abbr: 'A',
    tag: 'frist',
    tagLabel: 'Frist · ikke søgt endnu',
    heading: 'Digitaliseringskonsulent · Aabenraa Kommune',
    headingUrl: 'aabenraa.html',
    desc: 'IT-afdelingen, Aabenraa Kommune. Stillingen overvejes. Send ansøgning, CV og bilag senest 4. september.',
    calTitle: 'Ansøgningsfrist: Digitaliseringskonsulent · Aabenraa',
    calDesc: 'IT-afdelingen, Aabenraa Kommune. Stillingen overvejes. Send ansøgning, CV og bilag senest 4. september.',
    calUrl: 'aabenraa.html',
    cdLabel: 'Ansøgningsfrist: Aabenraa',
  },
  {
    start: '2026-09-10',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Indkaldelse',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Senest denne dato indkalder tvSyd kandidater til samtale. Ingen indkaldelse betyder afslag.',
    calTitle: 'Indkaldelse senest: Bestyrelsesmedlem · tvSyd',
    calDesc: 'Senest denne dato indkalder tvSyd kandidater til samtale. Ingen indkaldelse betyder afslag.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-09-10',
    kind: 'frist',
    abbr: 'F',
    tag: 'frist',
    tagLabel: 'Frist · send FØR',
    heading: 'Projektleder · Fleggaard IT',
    headingUrl: 'fleggaard.html',
    desc: 'Padborg. Samtaler afholdes løbende, og stillingen lukkes, når den rette er fundet, så send hurtigst muligt.',
    calTitle: 'Ansøgningsfrist: Projektleder · Fleggaard IT',
    calDesc: 'Samtaler afholdes løbende, og stillingen lukkes, når den rette er fundet, så send hurtigst muligt.',
    calUrl: 'fleggaard.html',
    cdLabel: 'Ansøgningsfrist: Fleggaard (løbende, send før)',
  },
  {
    start: '2026-09-15',
    kind: 'samtale',
    abbr: 'A',
    tag: 'samtale',
    tagLabel: 'Samtale (forventet)',
    heading: 'Digitaliseringskonsulent · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calTitle: 'Samtale (forventet): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calUrl: 'aabenraa.html',
  },
  {
    start: '2026-09-16',
    kind: 'samtale',
    abbr: 'A',
    tag: 'samtale',
    tagLabel: 'Samtale (forventet)',
    heading: 'Digitaliseringskonsulent · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calTitle: 'Samtale (forventet): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calUrl: 'aabenraa.html',
  },
  {
    start: '2026-08-17',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: 'Telefonaftale',
    heading: 'Telefonaftale · SFO-leder Berith (Jels)',
    headingUrl: 'jels.html',
    desc: 'Telefonaftale med SFO-leder Berith Nørgaard Hannesbo. Mellem 12 og 13 eller efter 14, tidspunktet bekræftes. Aftal rundvisningen, og brug spørgsmålene i fase 3.',
    calTitle: 'Telefonaftale: SFO-leder Berith Nørgaard Hannesbo (Jels)',
    calDesc: 'Mellem 12 og 13 eller efter 14, tidspunktet bekræftes. Aftal rundvisningen, og brug spørgsmålene i fase 3.',
    calUrl: 'jels.html',
    cdLabel: 'Telefonaftale: SFO-leder (Jels)',
  },
  {
    start: '2026-09-06',
    kind: 'frist',
    abbr: 'J',
    tag: 'frist',
    tagLabel: 'Frist · overvejes',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Vejen Kommune. Stillingen overvejes, beslut efter Vonsild/Sønderborg-udfaldet. Send ansøgning, CV og bilag via kommunens jobportal senest søndag den 6. september.',
    calTitle: 'Ansøgningsfrist: Skoleleder · Jels Skole',
    calDesc: 'Send ansøgning, CV og bilag via Vejen Kommunes jobportal senest søndag den 6. september.',
    calUrl: 'jels.html',
    cdLabel: 'Ansøgningsfrist: Jels Skole',
  },
  {
    start: '2026-09-14',
    kind: 'frist',
    abbr: 'C',
    tag: 'frist',
    tagLabel: 'Frist · benchmark, søges ikke',
    heading: 'Skolechef · Vejen Kommune (benchmark)',
    headingUrl: 'vejen-skolechef.html',
    desc: 'Slutmåls-benchmark, søges ikke. Fristen markerer, hvornår chef-ansættelsen går i gang, den afgør, hvem der bliver din chef i Jels-scenariet.',
    calTitle: 'Frist (benchmark, søges ikke): Skolechef · Vejen',
    calDesc: 'Slutmåls-benchmark, søges ikke. Ansættelsen afgør, hvem der bliver din chef i Jels-scenariet.',
    calUrl: 'vejen-skolechef.html',
  },
  {
    start: '2026-09-14',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: '1. samtale',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Første samtalerunde. Erhvervstest gennemføres mellem de to samtaler for kandidater, der går videre.',
    calTitle: '1. samtale: Skoleleder · Jels Skole',
    calDesc: 'Første samtalerunde. Erhvervstest gennemføres mellem de to samtaler for kandidater, der går videre.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-09-24',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: '2. samtale',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Anden samtalerunde med tilbagemelding på erhvervstesten.',
    calTitle: '2. samtale: Skoleleder · Jels Skole',
    calDesc: 'Anden samtalerunde med tilbagemelding på erhvervstesten.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-11-01',
    kind: 'tiltraedelse',
    abbr: 'J',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Jels Skole',
    headingUrl: 'jels.html',
    desc: 'Tiltrædelse 1. november 2026 eller snarest derefter.',
    calTitle: 'Tiltrædelse: Skoleleder · Jels Skole',
    calDesc: 'Tiltrædelse 1. november 2026 eller snarest derefter.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-10-01',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Bemærk kollision med forventet tiltrædelse Vonsild/Sønderborg.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Bemærk kollision med forventet tiltrædelse Vonsild/Sønderborg.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-10-02',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-10-19',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Afklar om 19. oktober er en anden runde.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Afklar om 19. oktober er en anden runde.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-10-01',
    kind: 'tiltraedelse',
    abbr: '',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Forventet opstart · Vonsild og Sønderborg',
    desc: 'Forventet startdato for Vonsild og Sønderborg. Vonsild Specialskole bliver selvstændig pr. 1. januar 2027.',
    calTitle: 'Forventet tiltrædelse (Vonsild og Sønderborg)',
    calDesc: 'Forventet startdato for Vonsild og Sønderborg. Vonsild Specialskole bliver selvstændig pr. 1. januar 2027.',
    cdLabel: 'Forventet tiltrædelse (Vonsild/Sønderborg)',
  },
  {
    start: '2026-11-02',
    kind: 'tiltraedelse',
    abbr: 'A',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Ønsket tiltrædelse for digitaliseringskonsulent-stillingen i Aabenraa Kommune.',
    calTitle: 'Tiltrædelse (ønsket): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Ønsket tiltrædelse for digitaliseringskonsulent-stillingen i Aabenraa Kommune.',
    calUrl: 'aabenraa.html',
  },
];
