// Fælles datakilde for alle datoer på siden.
// Både forsidens tidslinje, nedtællingen øverst og månedskalenderen
// (kalender.html) genereres af build.mjs ud fra denne ene liste, så en
// dato kun skal rettes ét sted.
//
// Felter pr. begivenhed:
//   start      ISO-dato (YYYY-MM-DD)
//   kind       frist | samtale | tiltraedelse (styrer farve i kalenderen)
//   abbr       kort bogstav-mærke i kalenderen der viser stillingen (tom = intet)
//   tag        pille-klasse på forsiden (tag--sendt, tag--samtale, ...)
//   tagLabel   teksten i pillen
//   heading    overskrift i tidslinjen
//   headingUrl gør overskriften til et link (udelad for ingen link)
//   desc       brødtekst i tidslinjen
//   calTitle   titel i .ics og som tooltip i kalenderen
//   calDesc    beskrivelse i .ics
//   calUrl     link lagt i .ics (udelad for ingen)
//   cdLabel    hvis sat, indgår datoen i nedtællingen med denne tekst

export const events = [
  {
    start: '2026-09-08',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: 'Telefonsamtale · kl. 17.30',
    heading: 'Telefonsamtale med vicedirektøren · SOSU Syd',
    headingUrl: 'sosu-syd.html',
    desc: 'Aftalt telefonsamtale tirsdag kl. 17.30. Afklar det tidligere valg, PAU-opgaven og lønrammen, før der bruges tid på ansøgning og video.',
    calTitle: 'Telefonsamtale: vicedirektør, SOSU Syd (kl. 17.30)',
    calDesc: 'Aftalt telefonsamtale om uddannelsesleder-stillingen. Spørgsmålene ligger i fase 3 på SOSU Syd-siden.',
    calUrl: 'sosu-syd.html',
    cdLabel: 'Telefonsamtale: SOSU Syd (kl. 17.30)',
  },
  {
    start: '2026-09-20',
    kind: 'frist',
    abbr: 'S',
    tag: 'frist',
    tagLabel: 'Frist · kl. 18',
    heading: 'Uddannelsesleder · SOSU Syd',
    headingUrl: 'sosu-syd.html',
    desc: 'Team GF, PAU og EUX. Bemærk det skarpe klokkeslæt, søndag den 20. september kl. 18.00, ikke midnat. Ansøgning, CV og videopræsentation på max 30 MB.',
    calTitle: 'Ansøgningsfrist: Uddannelsesleder · SOSU Syd (kl. 18)',
    calDesc: 'Send ansøgning, CV og videopræsentation senest søndag den 20. september kl. 18.00.',
    calUrl: 'sosu-syd.html',
  },
  {
    start: '2026-09-23',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: '1. samtale · efter kl. 12',
    heading: 'Uddannelsesleder · SOSU Syd',
    headingUrl: 'sosu-syd.html',
    desc: 'Første samtalerunde onsdag efter kl. 12. Bemærk Jels 2. samtale dagen efter, forberedelsen til begge skal ligge i weekenden inden.',
    calTitle: '1. samtale: Uddannelsesleder · SOSU Syd (efter kl. 12)',
    calDesc: 'Første samtalerunde onsdag den 23. september efter kl. 12.',
    calUrl: 'sosu-syd.html',
  },
  {
    start: '2026-09-29',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: '2. samtale · efter kl. 14',
    heading: 'Uddannelsesleder · SOSU Syd',
    headingUrl: 'sosu-syd.html',
    desc: 'Anden samtalerunde tirsdag efter kl. 14. Ligger midt i Jels-beslutningsvinduet, se de tre scenarier i fase 7.',
    calTitle: '2. samtale: Uddannelsesleder · SOSU Syd (efter kl. 14)',
    calDesc: 'Anden samtalerunde tirsdag den 29. september efter kl. 14.',
    calUrl: 'sosu-syd.html',
  },
  {
    start: '2026-11-01',
    kind: 'tiltraedelse',
    abbr: 'S',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · SOSU Syd',
    headingUrl: 'sosu-syd.html',
    desc: 'Tiltrædelse 1. november 2026 eller efter aftale, samme dato som Jels.',
    calTitle: 'Tiltrædelse: Uddannelsesleder · SOSU Syd',
    calDesc: 'Tiltrædelse 1. november 2026 eller efter aftale.',
    calUrl: 'sosu-syd.html',
  },
  {
    start: '2026-09-11',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: 'Besøg · kl. 13',
    heading: 'Besøg på Hærvejsskolen · konstitueret skoleleder',
    headingUrl: 'haervejsskolen.html#fase-3',
    desc: 'Aftalt besøg fredag kl. 13 hos den konstituerede skoleleder. Huskelisten ligger i fase 3, indtrykkene skrives ind i fase 4 samme dag.',
    calTitle: 'Besøg: Hærvejsskolen, konstitueret skoleleder (kl. 13)',
    calDesc: 'Aftalt besøg på skolen. Skovbrynet 2, Rødekro. Huskelisten ligger i fase 3 på Hærvejsskole-siden.',
    calUrl: 'haervejsskolen.html#fase-3',
    cdLabel: 'Besøg: Hærvejsskolen (kl. 13)',
  },
  {
    start: '2026-10-02',
    kind: 'frist',
    abbr: 'H',
    tag: 'frist',
    tagLabel: 'Frist · overvejes',
    heading: 'Skoleleder · Hærvejsskolen (Rødekro)',
    headingUrl: 'haervejsskolen.html',
    desc: 'Aabenraa Kommune. Søges parallelt med Jels, alle formelle krav er opfyldt. Send ansøgning, CV og bilag senest fredag den 2. oktober.',
    calTitle: 'Ansøgningsfrist: Skoleleder · Hærvejsskolen',
    calDesc: 'Send ansøgning, CV og bilag senest fredag den 2. oktober.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-20',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: '1. samtale · kl. 16',
    heading: 'Skoleleder · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Første samtalerunde tirsdag den 20. oktober fra kl. 16.',
    calTitle: '1. samtale: Skoleleder · Hærvejsskolen (kl. 16)',
    calDesc: 'Første samtalerunde fra kl. 16.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-21',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: 'Personprofil · 24 timer',
    heading: 'Personprofil-link · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Går jeg videre, kommer spørgeskemaet til personprofilen, udfyldes senest torsdag den 22. kl. 8.00. Reservér aftenen den 21. Tilbagemeldingssamtale fredag den 23.',
    calTitle: 'Personprofil-skema: Hærvejsskolen (frist 22/10 kl. 8)',
    calDesc: 'Spørgeskema til personprofil, udfyldes senest torsdag den 22. oktober kl. 8.00. Tilbagemeldingssamtale fredag den 23.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-28',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: '2. samtale · efter 18.30',
    heading: 'Skoleleder · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Anden samtalerunde onsdag den 28. oktober efter kl. 18.30, med tilbagemelding på personprofilen.',
    calTitle: '2. samtale: Skoleleder · Hærvejsskolen (efter 18.30)',
    calDesc: 'Anden samtalerunde efter kl. 18.30.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-12-01',
    kind: 'tiltraedelse',
    abbr: 'H',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Forventet tiltrædelse 1. december 2026.',
    calTitle: 'Tiltrædelse (forventet): Skoleleder · Hærvejsskolen',
    calDesc: 'Forventet tiltrædelse 1. december 2026.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-08',
    kind: 'frist',
    abbr: 'K',
    tag: 'frist',
    tagLabel: 'Frist · overvejes',
    heading: 'Afdelingsleder · Høje Kolstrup Skole',
    headingUrl: 'hoeje-kolstrup.html',
    desc: 'Aabenraa Kommune. Plan C bag Hærvejsskolen. Send ansøgning og CV senest torsdag den 8. oktober.',
    calTitle: 'Ansøgningsfrist: Afdelingsleder · Høje Kolstrup Skole',
    calDesc: 'Send ansøgning og CV senest torsdag den 8. oktober.',
    calUrl: 'hoeje-kolstrup.html',
  },
  {
    start: '2026-10-21',
    kind: 'samtale',
    abbr: 'K',
    tag: 'samtale',
    tagLabel: '1. samtale · dato afklares',
    heading: 'Afdelingsleder · Høje Kolstrup Skole',
    headingUrl: 'hoeje-kolstrup.html',
    desc: 'Opslaget skriver tirsdag den 21. oktober, men datoen er en onsdag. Afklar i opkaldet. Dagen efter Hærvejsskolens 1. samtale.',
    calTitle: '1. samtale: Afdelingsleder · Høje Kolstrup Skole (dato afklares)',
    calDesc: 'Første samtalerunde. Opslaget skriver tirsdag den 21. oktober, datoen er en onsdag.',
    calUrl: 'hoeje-kolstrup.html',
  },
  {
    start: '2026-10-23',
    kind: 'samtale',
    abbr: 'K',
    tag: 'samtale',
    tagLabel: 'Personprofil · 48 timer',
    heading: 'Personprofil-link · Høje Kolstrup Skole',
    headingUrl: 'hoeje-kolstrup.html',
    desc: 'Går jeg videre, kommer linket til personprofilen fredag den 23. med 48 timers svarfrist. Tilbagemelding fra ledelseskonsulenten før 2. samtale.',
    calTitle: 'Personprofil-link: Høje Kolstrup Skole (48 timer)',
    calDesc: 'Link til personprofil ved ledelseskonsulent, 48 timers svarfrist.',
    calUrl: 'hoeje-kolstrup.html',
  },
  {
    start: '2026-11-09',
    kind: 'samtale',
    abbr: 'K',
    tag: 'samtale',
    tagLabel: '2. samtale · efter kl. 18',
    heading: 'Afdelingsleder · Høje Kolstrup Skole',
    headingUrl: 'hoeje-kolstrup.html',
    desc: 'Anden samtalerunde mandag den 9. november efter kl. 18, med tilbagemelding på personprofilen forinden. Ligger efter Hærvejsskolens afgørelse.',
    calTitle: '2. samtale: Afdelingsleder · Høje Kolstrup Skole (efter kl. 18)',
    calDesc: 'Anden samtalerunde efter kl. 18. Personprofil-tilbagemelding forinden.',
    calUrl: 'hoeje-kolstrup.html',
  },
  {
    start: '2027-01-01',
    kind: 'tiltraedelse',
    abbr: 'K',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Afdelingsleder · Høje Kolstrup Skole',
    headingUrl: 'hoeje-kolstrup.html',
    desc: 'Ansættelse senest 1. januar 2027.',
    calTitle: 'Tiltrædelse: Afdelingsleder · Høje Kolstrup Skole',
    calDesc: 'Ansættelse senest 1. januar 2027.',
    calUrl: 'hoeje-kolstrup.html',
  },
];
