// Fælles datakilde for alle datoer på siden.
// Både forsidens tidslinje, nedtællingen øverst og månedskalenderen
// (kalender.html) genereres af build.mjs ud fra denne ene liste, så en
// dato kun skal rettes ét sted.
//
// Felter pr. begivenhed:
//   start      ISO-dato (YYYY-MM-DD)
//   kind       frist | samtale | tiltraedelse (styrer farve i kalenderen)
//   abbr       kort bogstav-mærke i kalenderen der viser stillingen (tom = intet)
//   tag        pille-klasse på forsiden (tag--sendt, tag--samtale, ...)
//   tagLabel   teksten i pillen
//   heading    overskrift i tidslinjen
//   headingUrl gør overskriften til et link (udelad for ingen link)
//   desc       brødtekst i tidslinjen
//   calTitle   titel i .ics og som tooltip i kalenderen
//   calDesc    beskrivelse i .ics
//   calUrl     link lagt i .ics (udelad for ingen)
//   cdLabel    hvis sat, indgår datoen i nedtællingen med denne tekst

export const events = [
  {
    start: '2026-08-31',
    kind: 'frist',
    abbr: 'T',
    tag: 'sendt',
    tagLabel: '✓ Sendt 2. august',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Ansøgning og CV er sendt 2. august 2026, næsten en måned før fristen, og modtagelsen er bekræftet.',
    calTitle: 'Ansøgningsfrist: Bestyrelsesmedlem · tvSyd',
    calDesc: 'Ansøgning og CV er sendt 2. august 2026, næsten en måned før fristen.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-08-31',
    kind: 'samtale',
    abbr: 'A',
    tag: 'samtale',
    tagLabel: 'Opkald · aftalt',
    heading: 'Opkald til Majbrit · digitaliseringskonsulent Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Aftalt opkald til IT-digitaliseringslederen mandag den 31. august. Afklar overkvalificeringen og lønrammen, og beslut derefter, om ansøgningen sendes før fristen fredag den 4. september.',
    calTitle: 'Opkald: Majbrit (digitaliseringskonsulent Aabenraa)',
    calDesc: 'Aftalt opkald til IT-digitaliseringslederen. Afklar overkvalificering og lønramme før ansøgningen.',
    calUrl: 'aabenraa.html',
    cdLabel: 'Opkald: Majbrit (Aabenraa)',
  },
  {
    start: '2026-09-04',
    kind: 'frist',
    abbr: 'A',
    tag: 'frist',
    tagLabel: 'Frist · ikke søgt endnu',
    heading: 'Digitaliseringskonsulent · Aabenraa Kommune',
    headingUrl: 'aabenraa.html',
    desc: 'IT-afdelingen, Aabenraa Kommune. Stillingen overvejes. Send ansøgning, CV og bilag senest 4. september.',
    calTitle: 'Ansøgningsfrist: Digitaliseringskonsulent · Aabenraa',
    calDesc: 'IT-afdelingen, Aabenraa Kommune. Stillingen overvejes. Send ansøgning, CV og bilag senest 4. september.',
    calUrl: 'aabenraa.html',
    cdLabel: 'Ansøgningsfrist: Aabenraa',
  },
  {
    start: '2026-09-10',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Indkaldelse',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Senest denne dato indkalder tvSyd kandidater til samtale. Ingen indkaldelse betyder afslag.',
    calTitle: 'Indkaldelse senest: Bestyrelsesmedlem · tvSyd',
    calDesc: 'Senest denne dato indkalder tvSyd kandidater til samtale. Ingen indkaldelse betyder afslag.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-09-15',
    kind: 'samtale',
    abbr: 'A',
    tag: 'samtale',
    tagLabel: 'Samtale (forventet)',
    heading: 'Digitaliseringskonsulent · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calTitle: 'Samtale (forventet): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calUrl: 'aabenraa.html',
  },
  {
    start: '2026-09-16',
    kind: 'samtale',
    abbr: 'A',
    tag: 'samtale',
    tagLabel: 'Samtale (forventet)',
    heading: 'Digitaliseringskonsulent · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calTitle: 'Samtale (forventet): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Samtaler forventes afholdt 15. og 16. september. Indkaldelsen afgør dag og tidspunkt.',
    calUrl: 'aabenraa.html',
  },
  {
    start: '2026-09-01',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: 'Besøg · kl. 7.30',
    heading: 'Besøg på Jels Skole',
    headingUrl: 'jels.html',
    desc: 'Besøg på skolen tirsdag kl. 7.30, aftalt med SFO-lederen. Fem dage før ansøgningsfristen, så besøget kan nævnes i ansøgningen.',
    calTitle: 'Besøg: Jels Skole (kl. 7.30)',
    calDesc: 'Besøg på skolen kl. 7.30, aftalt med SFO-lederen.',
    calUrl: 'jels.html',
    cdLabel: 'Besøg: Jels Skole (kl. 7.30)',
  },
  {
    start: '2026-09-06',
    kind: 'frist',
    abbr: 'J',
    tag: 'frist',
    tagLabel: 'Frist · hovedspor',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Vejen Kommune. Hovedsporet efter Vonsild-afslaget. Send ansøgning, CV og bilag via kommunens jobportal senest søndag den 6. september.',
    calTitle: 'Ansøgningsfrist: Skoleleder · Jels Skole',
    calDesc: 'Send ansøgning, CV og bilag via Vejen Kommunes jobportal senest søndag den 6. september.',
    calUrl: 'jels.html',
    cdLabel: 'Ansøgningsfrist: Jels Skole',
  },
  {
    start: '2026-09-13',
    kind: 'frist',
    abbr: 'S',
    tag: 'frist',
    tagLabel: 'Frist · overvejes',
    heading: 'Digitaliseringskonsulent · Sønderborg Kommune',
    headingUrl: 'soenderborg-digitalisering.html',
    desc: 'Digitalisering og Udbud. Backup-spor, Vonsild er afklaret, beslut nu. Send ansøgning, CV og bilag senest søndag den 13. september.',
    calTitle: 'Ansøgningsfrist: Digitaliseringskonsulent · Sønderborg',
    calDesc: 'Digitalisering og Udbud. Send ansøgning, CV og bilag senest søndag den 13. september.',
    calUrl: 'soenderborg-digitalisering.html',
  },
  {
    start: '2026-09-21',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: 'Samtale',
    heading: 'Digitaliseringskonsulent · Sønderborg',
    headingUrl: 'soenderborg-digitalisering.html',
    desc: 'Ansættelsessamtaler mandag den 21. september. Indkaldelsen afgør tidspunkt. Bemærk Jels-forløbet samme uge.',
    calTitle: 'Samtale: Digitaliseringskonsulent · Sønderborg',
    calDesc: 'Ansættelsessamtaler mandag den 21. september. Indkaldelsen afgør tidspunkt.',
    calUrl: 'soenderborg-digitalisering.html',
  },
  {
    start: '2026-09-22',
    kind: 'samtale',
    abbr: 'S',
    tag: 'samtale',
    tagLabel: 'Evt. 2. samtale',
    heading: 'Digitaliseringskonsulent · Sønderborg',
    headingUrl: 'soenderborg-digitalisering.html',
    desc: 'Eventuel 2. samtale tirsdag den 22. september.',
    calTitle: 'Evt. 2. samtale: Digitaliseringskonsulent · Sønderborg',
    calDesc: 'Eventuel 2. samtale tirsdag den 22. september.',
    calUrl: 'soenderborg-digitalisering.html',
  },
  {
    start: '2026-09-14',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: '1. samtale',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Første samtalerunde. Erhvervstest gennemføres mellem de to samtaler for kandidater, der går videre.',
    calTitle: '1. samtale: Skoleleder · Jels Skole',
    calDesc: 'Første samtalerunde. Erhvervstest gennemføres mellem de to samtaler for kandidater, der går videre.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-09-24',
    kind: 'samtale',
    abbr: 'J',
    tag: 'samtale',
    tagLabel: '2. samtale',
    heading: 'Skoleleder · Jels Skole (Vejen)',
    headingUrl: 'jels.html',
    desc: 'Anden samtalerunde med tilbagemelding på erhvervstesten.',
    calTitle: '2. samtale: Skoleleder · Jels Skole',
    calDesc: 'Anden samtalerunde med tilbagemelding på erhvervstesten.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-11-01',
    kind: 'tiltraedelse',
    abbr: 'J',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Jels Skole',
    headingUrl: 'jels.html',
    desc: 'Tiltrædelse 1. november 2026 eller snarest derefter.',
    calTitle: 'Tiltrædelse: Skoleleder · Jels Skole',
    calDesc: 'Tiltrædelse 1. november 2026 eller snarest derefter.',
    calUrl: 'jels.html',
  },
  {
    start: '2026-11-01',
    kind: 'tiltraedelse',
    abbr: 'S',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Sønderborg (digitalisering)',
    headingUrl: 'soenderborg-digitalisering.html',
    desc: 'Ønsket tiltrædelse 1. november eller efter aftale.',
    calTitle: 'Tiltrædelse (ønsket): Digitaliseringskonsulent · Sønderborg',
    calDesc: 'Ønsket tiltrædelse 1. november eller efter aftale.',
    calUrl: 'soenderborg-digitalisering.html',
  },
  {
    start: '2026-10-02',
    kind: 'frist',
    abbr: 'H',
    tag: 'frist',
    tagLabel: 'Frist · overvejes',
    heading: 'Skoleleder · Hærvejsskolen (Rødekro)',
    headingUrl: 'haervejsskolen.html',
    desc: 'Aabenraa Kommune. Plan B med hjemmebanefordel, beslut efter Vonsild, og afklar lærer-kravet først. Send ansøgning, CV og bilag senest fredag den 2. oktober.',
    calTitle: 'Ansøgningsfrist: Skoleleder · Hærvejsskolen',
    calDesc: 'Send ansøgning, CV og bilag senest fredag den 2. oktober.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-20',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: '1. samtale · kl. 16',
    heading: 'Skoleleder · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Første samtalerunde tirsdag den 20. oktober fra kl. 16.',
    calTitle: '1. samtale: Skoleleder · Hærvejsskolen (kl. 16)',
    calDesc: 'Første samtalerunde fra kl. 16.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-21',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: 'Personprofil · 24 timer',
    heading: 'Personprofil-link · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Går jeg videre, kommer spørgeskemaet til personprofilen, udfyldes senest torsdag den 22. kl. 8.00. Reservér aftenen den 21. Tilbagemeldingssamtale fredag den 23.',
    calTitle: 'Personprofil-skema: Hærvejsskolen (frist 22/10 kl. 8)',
    calDesc: 'Spørgeskema til personprofil, udfyldes senest torsdag den 22. oktober kl. 8.00. Tilbagemeldingssamtale fredag den 23.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-28',
    kind: 'samtale',
    abbr: 'H',
    tag: 'samtale',
    tagLabel: '2. samtale · efter 18.30',
    heading: 'Skoleleder · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Anden samtalerunde onsdag den 28. oktober efter kl. 18.30, med tilbagemelding på personprofilen.',
    calTitle: '2. samtale: Skoleleder · Hærvejsskolen (efter 18.30)',
    calDesc: 'Anden samtalerunde efter kl. 18.30.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-12-01',
    kind: 'tiltraedelse',
    abbr: 'H',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Hærvejsskolen',
    headingUrl: 'haervejsskolen.html',
    desc: 'Forventet tiltrædelse 1. december 2026.',
    calTitle: 'Tiltrædelse (forventet): Skoleleder · Hærvejsskolen',
    calDesc: 'Forventet tiltrædelse 1. december 2026.',
    calUrl: 'haervejsskolen.html',
  },
  {
    start: '2026-10-01',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-10-02',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-10-19',
    kind: 'samtale',
    abbr: 'T',
    tag: 'samtale',
    tagLabel: 'Samtale (mulig)',
    heading: 'Bestyrelsesmedlem · tvSyd',
    headingUrl: 'tvsyd.html',
    desc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Afklar om 19. oktober er en anden runde.',
    calTitle: 'Samtale (mulig): Bestyrelsesmedlem · tvSyd',
    calDesc: 'Samtaler afholdes 1., 2. og 19. oktober i Kolding. Afklar om 19. oktober er en anden runde.',
    calUrl: 'tvsyd.html',
  },
  {
    start: '2026-11-02',
    kind: 'tiltraedelse',
    abbr: 'A',
    tag: 'tiltraedelse',
    tagLabel: 'Tiltrædelse',
    heading: 'Tiltrædelse · Aabenraa',
    headingUrl: 'aabenraa.html',
    desc: 'Ønsket tiltrædelse for digitaliseringskonsulent-stillingen i Aabenraa Kommune.',
    calTitle: 'Tiltrædelse (ønsket): Digitaliseringskonsulent · Aabenraa',
    calDesc: 'Ønsket tiltrædelse for digitaliseringskonsulent-stillingen i Aabenraa Kommune.',
    calUrl: 'aabenraa.html',
  },
];
